#!/usr/bin/python

import cv2
import numpy as np

FPS = 30

video = cv2.VideoCapture("../samples/sample_florida1.mp4")
classifier = cv2.CascadeClassifier("../models/cars.xml")

kernel = np.ones((3, 3), np.uint8)
closing_kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (2, 2))

avg_bounding_box = np.zeros(4)

while video.isOpened():
    retcode, frame = video.read()

    if retcode != True:
        print("An error occured.")

    #other_space = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    #b_, g_, r_ = cv2.split(frame)

    #blue = np.array([b_, np.zeros_like(g_), r_])
    #blue = cv2.merge(blue)
    
    augmented = frame[200:600, 300:600]

    gray = cv2.cvtColor(augmented, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    dilated = cv2.dilate(blurred, kernel)
    closing = cv2.morphologyEx(dilated, cv2.MORPH_CLOSE, closing_kernel)
   
    result = classifier.detectMultiScale(augmented, 1.0007, 4, 0, (120,120))

    for rect in result:
        x, y, width, height = rect

        # 10% Tolerance
        x += x // 10
        y += y // 10

        cv2.rectangle(augmented, (x, y), (x + width, y + height), (0, 255, 0))

    cv2.imshow("Sample Video", augmented)

    if cv2.waitKey(int(1000 / FPS)) == ord('e'):
        break

video.release()
cv2.destroyAllWindows()

def main():
    pass

if __name__ == "__main__":
    main()
